# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, max_length=11, verbose_name='\u6d88\u8d39\u65f6\u95f4')),
                ('bank_name', models.CharField(max_length=100, verbose_name='\u94f6\u884c\u540d\u79f0')),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u4ea4\u6613\u91d1\u989d')),
                ('turnOut_AccountNumber', models.IntegerField(verbose_name='\u8f6c\u51fa\u8d26\u53f7')),
                ('into_AccountNumber', models.IntegerField(verbose_name='\u8f6c\u5165\u8d26\u53f7')),
                ('into_name', models.CharField(max_length=30, verbose_name='\u8f6c\u5165\u6237\u540d')),
                ('consumption_business', models.CharField(max_length=100, null=True, verbose_name='\u6d88\u8d39\u5546\u5bb6')),
                ('consumption_commodity', models.CharField(max_length=100, null=True, verbose_name='\u6d88\u8d39\u5546\u54c1')),
                ('consumption_type', models.CharField(choices=[('0', '\u626b\u7801\u652f\u4ed8'), ('1', '\u7b2c\u4e09\u65b9\u652f\u4ed8')], default=0, max_length=100, verbose_name='\u6d88\u8d39\u7c7b\u578b')),
            ],
            options={
                'verbose_name': '\u6d88\u8d39\u8bb0\u5f55',
                'verbose_name_plural': '\u6d88\u8d39\u8bb0\u5f55',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, max_length=11, verbose_name='\u6d88\u8d39\u65f6\u95f4')),
                ('bank_name', models.CharField(max_length=100, verbose_name='\u94f6\u884c\u540d\u79f0')),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u4ea4\u6613\u91d1\u989d')),
                ('turnOut_AccountNumber', models.IntegerField(verbose_name='\u8f6c\u51fa\u8d26\u53f7')),
                ('into_AccountNumber', models.IntegerField(verbose_name='\u8f6c\u5165\u8d26\u53f7')),
                ('into_name', models.CharField(max_length=30, verbose_name='\u8f6c\u5165\u6237\u540d')),
                ('consumption_business', models.CharField(max_length=100, null=True, verbose_name='\u6d88\u8d39\u5546\u5bb6')),
                ('consumption_commodity', models.CharField(max_length=100, null=True, verbose_name='\u6d88\u8d39\u5546\u54c1')),
                ('consumption_type', models.CharField(choices=[('0', '\u626b\u7801\u652f\u4ed8'), ('1', '\u7b2c\u4e09\u65b9\u652f\u4ed8')], default=0, max_length=100, verbose_name='\u6d88\u8d39\u7c7b\u578b')),
            ],
            options={
                'verbose_name': '\u5408\u7ea6\u8bb0\u5f55',
                'verbose_name_plural': '\u5408\u7ea6\u8bb0\u5f55',
            },
        ),
    ]
