# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('mobile', models.CharField(max_length=64, verbose_name='\u624b\u673a\u53f7')),
                ('code', models.CharField(default='0', max_length=10, verbose_name='\u9a8c\u8bc1\u7801')),
                ('status', models.CharField(choices=[('ready', '\u5df2\u8bfb'), ('unread', '\u672a\u8bfb')], max_length=10, verbose_name='\u72b6\u6001')),
            ],
            options={
                'verbose_name': '\u9a8c\u8bc1\u7801',
                'verbose_name_plural': '\u9a8c\u8bc1\u7801',
            },
        ),
    ]
