# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 15:56
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields
import model_utils.fields
import service.consumer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.UUIDField(auto_created=True, blank=True, null=True, verbose_name='slug')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('mobile', models.CharField(blank=True, db_index=True, max_length=25, verbose_name='\u624b\u673a\u53f7\u7801')),
                ('verify_code', models.CharField(blank=True, max_length=5, verbose_name='\u77ed\u4fe1\u7801')),
                ('device', models.CharField(max_length=100, verbose_name='\u8bbe\u5907\u53f7')),
                ('jpush_registration_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='jpush_registration_id')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', service.consumer.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('city', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='\u57ce\u5e02')),
                ('area', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='\u5e02\u533a')),
                ('address', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='\u8be6\u7ec6\u5730\u5740')),
                ('default', models.BooleanField(default=False, verbose_name='\u9ed8\u8ba4\u5730\u5740')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u7528\u6237\u5730\u5740',
                'verbose_name_plural': '\u7528\u6237\u5730\u5740',
            },
        ),
        migrations.CreateModel(
            name='Affairs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('default', models.BooleanField(default=False, verbose_name='\u7528\u6237\u901a\u8baf\u5f55')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affairs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u7528\u6237\u901a\u8baf\u5f55',
                'verbose_name_plural': '\u7528\u6237\u901a\u8baf\u5f55',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('default', models.BooleanField(default=False, verbose_name='\u7528\u6237\u901a\u8baf\u5f55')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u7528\u6237\u901a\u8baf\u5f55',
                'verbose_name_plural': '\u7528\u6237\u901a\u8baf\u5f55',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='\u59d3\u540d')),
                ('nick', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='\u6635\u79f0')),
                ('phone', models.CharField(blank=True, default='', max_length=64, verbose_name='\u7535\u8bdd')),
                ('gender', models.CharField(choices=[('male', '\u7537'), ('female', '\u5973')], default='male', max_length=10, verbose_name='\u6027\u522b')),
                ('zodiac', models.CharField(blank=True, max_length=25, verbose_name='\u661f\u5ea7')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='\u751f\u65e5')),
                ('alipay', models.CharField(blank=True, max_length=100, verbose_name='\u652f\u4ed8\u5b9d')),
                ('qq', models.CharField(blank=True, max_length=100, verbose_name='QQ')),
                ('chinese_zodiac', models.CharField(blank=True, max_length=25, verbose_name='\u751f\u8096')),
                ('payment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='\u5df2\u7ecf\u63d0\u73b0')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='\u5e10\u6237\u4f59\u989d')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='\u5e10\u6237\u603b\u989d')),
                ('qrcode', models.ImageField(upload_to='qrcode', verbose_name='\u4e8c\u7ef4\u7801')),
                ('avatar', imagekit.models.fields.ProcessedImageField(null=True, upload_to='avatar', verbose_name='\u5934\u50cf')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
    ]
