# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 15:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0003_auto_20161122_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL),
        ),
    ]
