# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 10:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0007_auto_20161122_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bankcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='\u6240\u5c5e\u94f6\u884c')),
                ('number', models.CharField(blank=True, max_length=50, verbose_name='\u94f6\u884c\u5361\u5361\u53f7')),
                ('ctime', models.DateField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4\uff0c\u7cfb\u7edf\u81ea\u5efa')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u7528\u6237\u94f6\u884c\u5361',
                'verbose_name_plural': '\u7528\u6237\u94f6\u884c\u5361',
            },
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=50, verbose_name='\u7528\u6237ID')),
                ('ctime', models.DateField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4\uff0c\u7cfb\u7edf\u81ea\u5efa')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u7528\u6237\u9ed1\u540d\u5355',
                'verbose_name_plural': '\u7528\u6237\u9ed1\u540d\u5355',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='\u59d3\u540d')),
                ('nick', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='\u9a6c\u7532')),
                ('phone', models.CharField(blank=True, default='', max_length=64, verbose_name='\u7535\u8bdd')),
                ('type_phone', models.BooleanField(default=False, verbose_name='\u7535\u8bdd\u53f7\u7801\u7ed1\u5b9a\u72b6\u6001')),
                ('id_card', models.CharField(blank=True, default='', max_length=64, verbose_name='\u8bc1\u4ef6\u53f7\u7801')),
                ('document_type', models.CharField(choices=[('identity', '\u5c45\u6c11\u8eab\u4efd\u8bc1'), ('driver', '\u9a7e\u9a76\u8bc1'), ('officers', '\u519b\u5b98\u8bc1'), ('passport', '\u62a4\u7167')], default='identity', max_length=10, verbose_name='\u8bc1\u4ef6\u7c7b\u578b')),
                ('id_identity', models.BooleanField(default=False, verbose_name='\u8eab\u4efd\u8ba4\u8bc1')),
                ('avatar', imagekit.models.fields.ProcessedImageField(null=True, upload_to='avatar', verbose_name='\u5934\u50cf')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'settings',
                'verbose_name_plural': 'settings',
            },
        ),
    ]
