# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 15:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0008_bankcard_blacklist_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklist',
            name='ctime',
        ),
        migrations.RemoveField(
            model_name='blacklist',
            name='user_id',
        ),
        migrations.AddField(
            model_name='blacklist',
            name='black',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='black', to=settings.AUTH_USER_MODEL, verbose_name='\u9ed1\u540d\u5355\u7528\u6237'),
        ),
        migrations.AddField(
            model_name='blacklist',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='blacklist',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
