# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0009_auto_20161129_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affairs',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='bankcard',
            name='ctime',
        ),
        migrations.RemoveField(
            model_name='bankcard',
            name='name',
        ),
        migrations.RemoveField(
            model_name='bankcard',
            name='number',
        ),
        migrations.AddField(
            model_name='bankcard',
            name='bank',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='\u6240\u5c5e\u94f6\u884c'),
        ),
        migrations.AddField(
            model_name='bankcard',
            name='card',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='\u94f6\u884c\u5361\u53f7'),
        ),
        migrations.AddField(
            model_name='bankcard',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='bankcard',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.DeleteModel(
            name='Affairs',
        ),
    ]
