# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 16:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0010_auto_20161129_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='default',
        ),
        migrations.AddField(
            model_name='contact',
            name='friend',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='friends', to=settings.AUTH_USER_MODEL, verbose_name='\u597d\u53cb'),
        ),
    ]
