# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0011_auto_20161129_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankcard',
            name='suffix',
            field=models.CharField(default='', max_length=10, verbose_name='\u5361\u53f7\u540e\u7f00'),
        ),
        migrations.AddField(
            model_name='bankcard',
            name='type',
            field=models.CharField(choices=[('\u50a8\u84c4\u5361', '\u50a8\u84c4\u5361')], default='', max_length=10, verbose_name='\u5361\u7247\u7c7b\u578b'),
        ),
    ]
