# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0013_bankcard_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcard',
            name='flag',
            field=models.CharField(choices=[('\u6536', '\u6536')], default='', max_length=10, verbose_name='\u5361\u7247\u7528\u9014'),
        ),
    ]
