# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0014_auto_20161130_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='friend_verify',
            field=models.BooleanField(default=False, verbose_name='\u52a0\u597d\u53cb\u65f6\u662f\u5426\u9a8c\u8bc1'),
        ),
        migrations.AddField(
            model_name='settings',
            name='mobile_verify',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u5141\u8bb8\u624b\u673a\u53f7\u67e5\u627e'),
        ),
        migrations.AddField(
            model_name='settings',
            name='public_name',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u516c\u5f00\u59d3\u540d'),
        ),
    ]
