# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0015_auto_20161204_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='alipay',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='total',
        ),
        migrations.AddField(
            model_name='profile',
            name='friend_verify',
            field=models.BooleanField(default=False, verbose_name='\u52a0\u597d\u53cb\u65f6\u662f\u5426\u9a8c\u8bc1'),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile_verify',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u5141\u8bb8\u624b\u673a\u53f7\u67e5\u627e'),
        ),
        migrations.AddField(
            model_name='profile',
            name='name_public',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u516c\u5f00\u59d3\u540d'),
        ),
    ]
