# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 21:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0017_contact_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('contains', models.TextField(default='', verbose_name='\u624b\u673a\u901a\u8baf\u5f55\u6570\u636e')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u624b\u673a\u901a\u8baf\u5f55',
                'verbose_name_plural': '\u624b\u673a\u901a\u8baf\u5f55',
            },
        ),
    ]
