# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 02:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0018_contains'),
        ('consumer', '0016_merge_20161205_2031'),
    ]

    operations = [
    ]
