# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0018_contains'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='hide',
            field=models.BooleanField(default=False, verbose_name='\u522b\u4eba\u4e0d\u53ef\u89c1\u771f\u540d'),
        ),
    ]
