# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0019_contact_hide'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='level',
            field=models.CharField(default='', max_length=100, verbose_name='\u7528\u6237\u7b49\u7ea7'),
            preserve_default=False,
        ),
    ]
