# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 21:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0019_merge_20161207_0208'),
        ('consumer', '0019_contact_hide'),
    ]

    operations = [
    ]
