# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 00:35
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0020_customuser_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='invite', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='contact',
            name='status_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed'),
        ),
    ]
