# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 00:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0020_merge_20161207_2158'),
        ('consumer', '0021_auto_20161212_0035'),
    ]

    operations = [
    ]
