# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0022_merge_20161212_0059'),
        ('consumer', '0022_merge_20161212_0052'),
    ]

    operations = [
    ]
