# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0002_auto_20161129_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
