# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0005_auto_20161205_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('key', models.CharField(default='', max_length=200, unique=True)),
                ('dn', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name': '\u8eab\u4efd\u9a8c\u8bc1',
                'verbose_name_plural': '\u8eab\u4efd\u9a8c\u8bc1',
            },
        ),
    ]
