# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0006_validate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identity',
            old_name='bankcard',
            new_name='bankID',
        ),
        migrations.RenameField(
            model_name='identity',
            old_name='id_card',
            new_name='certId',
        ),
        migrations.RemoveField(
            model_name='identity',
            name='card_type',
        ),
        migrations.RemoveField(
            model_name='identity',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='identity',
            name='signs',
        ),
        migrations.AddField(
            model_name='identity',
            name='address',
            field=models.CharField(default='', max_length=200, verbose_name='\u8be6\u7ec6\u5730\u5740'),
        ),
        migrations.AddField(
            model_name='identity',
            name='backPhoto',
            field=models.CharField(default='', max_length=200, verbose_name='\u8be6\u7ec6\u5730\u5740'),
        ),
        migrations.AddField(
            model_name='identity',
            name='cardNo',
            field=models.CharField(default='', max_length=100, verbose_name='\u94f6\u884c\u5361\u53f7'),
        ),
        migrations.AddField(
            model_name='identity',
            name='certType',
            field=models.IntegerField(default='1', verbose_name='\u5361\u7247\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='identity',
            name='cvn2',
            field=models.CharField(default='', max_length=200, verbose_name='\u8be6\u7ec6\u5730\u5740'),
        ),
        migrations.AddField(
            model_name='identity',
            name='frontPhoto',
            field=models.CharField(default='', max_length=200, verbose_name='\u8be6\u7ec6\u5730\u5740'),
        ),
    ]
