# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 04:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signature', '0007_auto_20161206_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
