# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 15:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='im_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
