# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields
import model_utils.fields
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(default='', max_length=50, verbose_name='\u5730\u533a')),
                ('site', models.CharField(default='', max_length=50, verbose_name='\u57ce\u5e02')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u8be6\u7ec6\u5730\u5740')),
            ],
            options={
                'verbose_name': '\u5ba2\u6237\u5730\u5740',
                'verbose_name_plural': '\u5ba2\u6237\u5730\u5740',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u5206\u7c7b\u540d\u79f0')),
                ('cover', models.ImageField(blank=True, max_length=200, null=True, upload_to='category', verbose_name='\u5206\u7c7b\u56fe\u7247')),
                ('total', models.IntegerField(blank=True, default=0, null=True, verbose_name='\u5546\u54c1\u6570')),
                ('order', models.PositiveIntegerField(default=999, editable=False, verbose_name='\u6392\u5e8f')),
                ('channel', models.CharField(choices=[('1000', '\u5b98\u7f51'), ('1001', '91\u52a9\u624b'), ('1002', '\u767e\u5ea6'), ('1003', '\u5b89\u5353'), ('1004', '\u8c4c\u8c46\u835a'), ('1005', '\u5e94\u7528\u5b9d'), ('1006', '360'), ('1007', '\u5e94\u7528\u6c47'), ('1008', '\u9b45\u65cf'), ('1009', 'N\u591a\u7f51'), ('1010', 'PP\u52a9\u624b'), ('1011', '\u6dd8\u5b9d'), ('1012', '\u673a\u950b\u7f51'), ('1013', '\u91d1\u7acb'), ('1014', '\u5c0f\u7c73'), ('1015', '\u534e\u4e3a'), ('1016', '\u641c\u72d7'), ('1017', '\u5b89\u667a'), ('1018', '\u6c83\u5546\u5e97'), ('1019', 'itools'), ('1020', '\u7535\u4fe1\u7231\u6e38\u620f'), ('1021', '\u4f18\u4ebf\u5e02\u573a'), ('1022', '\u5e94\u7528\u8d1d'), ('1023', 'googleplay'), ('1024', '\u5b89\u7c89\u7f51')], max_length=100, verbose_name='chanell')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='kernel.Category')),
            ],
            options={
                'verbose_name': '\u5546\u54c1\u7c7b\u522b',
                'verbose_name_plural': '\u5546\u54c1\u7c7b\u522b',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='\u540d\u79f0')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='\u4ef7\u683c')),
                ('units', models.CharField(max_length=50, verbose_name='\u5355\u4f4d')),
                ('order', models.IntegerField(default='1', verbose_name='\u6392\u5e8f')),
                ('cover', imagekit.models.fields.ProcessedImageField(help_text='\u56fe\u7247\u5c3a\u5bf8\u6700\u597d\u4e3a720x240', null=True, upload_to='goods', verbose_name='\u56fe\u7247')),
            ],
            options={
                'verbose_name': '\u5ba2\u6237\u5217\u8868',
                'verbose_name_plural': '\u5ba2\u6237\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('draft', 'draft'), ('published', 'published')], default='draft', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('name', models.CharField(default='', max_length=100, verbose_name='\u540d\u79f0')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='\u4ef7\u683c')),
                ('units', models.CharField(choices=[('ios', 'IOS'), ('android', 'Android')], max_length=50, verbose_name='\u5355\u4f4d')),
                ('order', models.IntegerField(default='1', verbose_name='\u6392\u5e8f')),
                ('cover', imagekit.models.fields.ProcessedImageField(help_text='\u56fe\u7247\u5c3a\u5bf8\u6700\u597d\u4e3a720x240', null=True, upload_to='goods', verbose_name='\u56fe\u7247')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kernel.Category')),
            ],
            options={
                'verbose_name': '\u5546\u54c1\u5217\u8868',
                'verbose_name_plural': '\u5546\u54c1\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u5206\u7c7b\u540d\u79f0')),
                ('slug', models.SlugField(blank=True, default='', null=True, verbose_name='Slug')),
                ('cover', models.ImageField(blank=True, max_length=200, upload_to='category', verbose_name='\u5206\u7c7b\u56fe\u7247')),
                ('ordering', models.PositiveIntegerField(default=999, editable=False, verbose_name='\u6392\u5e8f')),
                ('is_active', models.BooleanField(default=False, verbose_name='\u6fc0\u6d3b')),
                ('keyword', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5206\u7c7b\u5173\u952e\u5b57')),
                ('channel', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u9891\u9053')),
                ('catids', models.BigIntegerField(blank=True, null=True, verbose_name='\u6dd8\u5b9d\u5206\u7c7b')),
                ('total', models.IntegerField(blank=True, default=0, null=True, verbose_name='\u5546\u54c1\u6570')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='kernel.Groups')),
            ],
            options={
                'verbose_name': '\u5ba2\u6237\u5206\u7ec4',
                'verbose_name_plural': '\u5ba2\u6237\u5206\u7ec4',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='', max_length=100, verbose_name='\u8ba2\u5355\u53f7')),
                ('address', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='\u4ef7\u683c')),
                ('units', models.CharField(max_length=50, verbose_name='\u5355\u4f4d')),
                ('order', models.IntegerField(default='1', verbose_name='\u6392\u5e8f')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kernel.Client')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kernel.Goods')),
            ],
            options={
                'verbose_name': '\u8ba2\u5355\u5217\u8868',
                'verbose_name_plural': '\u8ba2\u5355\u5217\u8868',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='groups',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kernel.Groups'),
        ),
        migrations.AddField(
            model_name='address',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kernel.Client'),
        ),
    ]
