# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0002_transfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certufucate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certufucate_num', models.IntegerField(verbose_name='\u8bc1\u4e66\u53f7')),
                ('certufucate_name', models.CharField(max_length=100, verbose_name='\u8bc1\u4e66\u6301\u6709\u4eba')),
                ('credentials_type', models.IntegerField(choices=[('0', '\u8eab\u4efd\u8bc1'), ('1', 'EID'), ('2', '3')], default=0, verbose_name='\u8bc1\u4ef6\u7c7b\u578b')),
                ('credentials_num', models.CharField(max_length=100, verbose_name='\u8bc1\u4ef6\u53f7')),
                ('certification_authority', models.CharField(max_length=100, verbose_name='\u53d1\u8bc1\u673a\u6784')),
                ('certufucate_status', models.BooleanField(default=True, verbose_name='\u8bc1\u4e66\u72b6\u6001')),
                ('certufucate_level', models.CharField(choices=[('0', 'A'), ('1', 'B'), ('2', 'C'), ('3', 'D')], default=0, max_length=10, verbose_name='\u8bc1\u4e66\u7b49\u7ea7')),
                ('authentication_mode', models.CharField(choices=[('0', '\u8fdc\u7a0b\u67dc\u53f0'), ('1', '\u94f6\u884c\u67dc\u53f0')], default=0, max_length=10, verbose_name='\u8ba4\u8bc1\u65b9\u5f0f')),
                ('credit_level', models.CharField(choices=[('0', 'A-10'), ('1', 'B-10'), ('2', 'C-10')], max_length=100, verbose_name='\u4fe1\u7528\u7b49\u7ea7')),
                ('termOfValidity', models.DateTimeField(max_length=11, verbose_name='\u6709\u6548\u671f')),
            ],
            options={
                'verbose_name': '\u6570\u5b57\u8bc1\u4e66',
                'verbose_name_plural': '\u6570\u5b57\u8bc1\u4e66',
            },
        ),
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, max_length=11, verbose_name='\u6d88\u8d39\u65f6\u95f4')),
                ('bank_name', models.CharField(max_length=100, verbose_name='\u94f6\u884c\u540d\u79f0')),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u4ea4\u6613\u91d1\u989d')),
                ('turnOut_AccountNumber', models.IntegerField(verbose_name='\u8f6c\u51fa\u8d26\u53f7')),
                ('into_AccountNumber', models.IntegerField(verbose_name='\u8f6c\u5165\u8d26\u53f7')),
                ('into_name', models.CharField(max_length=30, verbose_name='\u8f6c\u5165\u6237\u540d')),
                ('consumption_business', models.CharField(max_length=100, null=True, verbose_name='\u6d88\u8d39\u5546\u5bb6')),
                ('consumption_commodity', models.CharField(max_length=100, null=True, verbose_name='\u6d88\u8d39\u5546\u54c1')),
                ('consumption_type', models.CharField(choices=[(0, '\u94b1\u5305'), (1, '\u94f6\u884c\u5361'), (2, '\u57fa\u91d1')], default=0, max_length=11, verbose_name='\u6d88\u8d39\u7c7b\u578b')),
            ],
            options={
                'verbose_name': '\u6d88\u8d39\u8bb0\u5f55',
                'verbose_name_plural': '\u6d88\u8d39\u8bb0\u5f55',
            },
        ),
    ]
