# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0005_auto_20161124_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='transfer_type',
            field=models.CharField(choices=[('198', '\u6536\u6b3e'), ('199', '\u8f6c\u8d26')], default=199, max_length=100, verbose_name='\u8f6c\u8d26\u7c7b\u578b'),
        ),
    ]
