# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0008_auto_20161124_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise_name', models.CharField(max_length=100, verbose_name='\u4f01\u4e1a\u540d\u79f0')),
                ('bank_accountType', models.CharField(choices=[('0', '\u5bf9\u516c\u94f6\u884c\u8d26\u6237'), ('1', '\u5bf9\u79c1\u94f6\u884c\u8d26\u6237')], default=0, max_length=100, verbose_name='\u94f6\u884c\u8d26\u6237\u7c7b\u578b')),
                ('bank_accountName', models.CharField(max_length=100, verbose_name='\u94f6\u884c\u5f00\u6237\u540d')),
                ('bank_num', models.IntegerField(verbose_name='\u94f6\u884c\u8d26\u53f7')),
                ('bank_account', models.CharField(choices=[('0', '\u5de5\u5546\u94f6\u884c'), ('1', '\u519c\u4e1a\u94f6\u884c'), ('2', '\u5efa\u8bbe\u94f6\u884c'), ('3', '\u4e2d\u56fd\u94f6\u884c'), ('4', '\u4e2d\u4fe1\u5b9e\u4e1a\u94f6\u884c'), ('5', '\u6052\u4e30\u94f6\u884c'), ('6', '\u5e7f\u4e1c\u53d1\u5c55\u94f6\u884c'), ('7', '\u6df1\u5733\u53d1\u5c55\u94f6\u884c'), ('8', '\u5149\u5927\u94f6\u884c')], default=0, max_length=100, verbose_name='\u5f00\u6237\u94f6\u884c')),
                ('bank_add', models.CharField(max_length=100, verbose_name='\u5f00\u6237\u94f6\u884c\u6240\u5728\u5730')),
                ('bank_branch', models.CharField(max_length=200, verbose_name='\u5f00\u6237\u94f6\u884c\u652f\u884c\u540d\u79f0')),
                ('yesterday_income', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u6628\u65e5\u6536\u5165\u603b\u8ba1')),
                ('platform_income', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u5e73\u53f0\u6536\u5165\u603b\u8ba1')),
                ('settled_date', models.DateTimeField(auto_now=True, verbose_name='\u5165\u9a7b\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u4f01\u4e1a\u7528\u6237',
                'verbose_name_plural': '\u4f01\u4e1a\u7528\u6237',
            },
        ),
    ]
