# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0010_auto_20161128_1503'),
        ('kernel', '0011_auto_20161128_1533'),
    ]

    operations = [
    ]
