# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0013_relancement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certufucate',
            name='credentials_type',
            field=models.CharField(choices=[('1110', '\u8eab\u4efd\u8bc1'), ('1111', 'EID'), ('1112', '3')], default=1110, max_length=100, verbose_name='\u8bc1\u4ef6\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='certufucate',
            name='termOfValidity',
            field=models.DateField(max_length=11, verbose_name='\u6709\u6548\u671f'),
        ),
        migrations.AlterField(
            model_name='relancement',
            name='creation_time',
            field=models.DateField(auto_now_add=True, verbose_name='\u7533\u8bf7\u65f6\u95f4'),
        ),
    ]
