# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0014_auto_20161129_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certufucate',
            name='credentials_type',
            field=models.CharField(choices=[('1110', '\u8eab\u4efd\u8bc1'), ('1111', 'EID'), ('1112', '3')], default=1110, max_length=100, verbose_name='\u8bc1\u4ef6\u7c7b\u578b'),
        ),
    ]
