# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 23:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0016_auto_20161130_1006'),
        ('kernel', '0018_auto_20161129_1407'),
        ('kernel', '0014_auto_20161130_0942'),
    ]

    operations = [
    ]
