# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0019_merge_20161201_2344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relancement',
            options={'verbose_name': '\u521b\u5efa\u516c\u544a', 'verbose_name_plural': '\u516c\u544a\u7ba1\u7406'},
        ),
    ]
