# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0020_auto_20161204_2105'),
        ('kernel', '0021_report'),
    ]

    operations = [
    ]
