# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0022_merge_20161205_2031'),
        ('kernel', '0022_invite'),
    ]

    operations = [
    ]
